# Generated by Django 2.2.10 on 2020-02-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_registraion_data',
            name='emp_username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
